version: "3"

services:
  cut-modelserver:
    container_name: "CUT-Modelserver"
    build: .
    ports:
      - "8888:5555"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cut-modelserver.entrypoints=https"
      - "traefik.http.routers.cut-modelserver.tls=true"
      - "traefik.http.routers.cut-modelserver.tls.certresolver=lets-encr"
      - "traefik.http.routers.cut-modelserver.rule=Host(`modelserver.cut.hcu-hamburg.de`)"
      - "traefik.http.middlewares.modelserver-authenticator.basicauth.users=cut:$$2a$$12$$UEdt/AT9zZDaqBHlXMROsebOXlet6nQH7eAAgeWtXfnP/gxyadb9m "
      - "traefik.http.routers.cut-modelserver.middlewares=modelserver-authenticator@docker"
    networks:
      - proxy
      - websocket-simulation

networks:
  proxy:
    external: true
  websocket-simulation:
    external: true